config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :tasks, only: %i[index create] do
    member do
      get 'complete'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  layout false

  def index
    @tasks = Task.order('created_at DESC')
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    return unless @task.save

    ActionCable.server.broadcast('tasks_channel', {})
  end

  def complete
    @task = Task.find(params[:id])
    @task.update(completed: true)

    ActionCable.server.broadcast('tasks_channel', {})
  end

  private

  def task_params
    params.require(:task).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div data-controller='tasks' data-tasks-url-value="<%= tasks_path %>" data-tasks-target='listing'></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoStimulusExample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task, remote: true, data: { action: 'ajax:success->tasks#load'}) do |f| %>
  <%= f.text_field :title
  <%= f.submit "Add" %>
<% end %>

app/views/tasks/_task.html.erb
<li>
  <% if task.completed %>
    <s><%= task.title %></s>
  <% else %>
    <%= task.title %> - <%= link_to('Complete',
    complete_task_path(task), remote: true, data: { action: 'ajax:success->tasks#load'}) %>
  <% end %>
</li>

app/views/tasks/index.html.erb
<h1>Tasks:</h1>

<ul>
  <% @tasks.each do |task| %>
    <%= render 'task', task: task %>
  <% end %>
</ul>